[package]
name = "chromiant"
version = "0.1.0"
edition = "2024"
description = "A library to search for colors from a curated collection of unique color names."
license = "MIT"
readme = "README.md"
keywords = ["color", "hsl", "rgb", "hex"]
homepage = "https://github.com/rivea0/chromiant"
repository = "https://github.com/rivea0/chromiant"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
csv = "1.4.0"
reqwest = { version = "0.13", features = ["blocking", "json"] }
jiff = "0.2.37"
dirs = "7.0"
colorsys = "0.7"

[dev-dependencies]
tempfile = "3.27.0"
mockall = "0.15.0"